brew "asdf"
brew "fish"
brew "fzf"
brew "git"
brew "git-lfs"
brew "gnu-sed"
brew "htop"
brew "jq"
brew "mackup" unless OS.linux?
brew "postgresql"
brew "redis"
brew "stow"
brew "tree"
brew "vim"
brew "xclip" if OS.linux?

# GUI applications (macOS only)
cask "alfred" unless OS.linux?
cask "brave-browser" unless OS.linux?
cask "caffeine" unless OS.linux?
cask "charles" unless OS.linux?
cask "cheatsheet" unless OS.linux?
cask "daisydisk" unless OS.linux?
cask "dash" unless OS.linux?
cask "discord" unless OS.linux?
cask "docker" unless OS.linux?
cask "firefox" unless OS.linux?
cask "ferdium" unless OS.linux?
cask "google-chrome" unless OS.linux?
cask "google-cloud-sdk" unless OS.linux?
cask "jetbrains-toolbox" unless OS.linux?
cask "ghostty" unless OS.linux?
cask "postico" unless OS.linux?
cask "postman" unless OS.linux?
cask "rectangle" unless OS.linux?
cask "slack" unless OS.linux?
cask "spotify" unless OS.linux?
cask "visual-studio-code" unless OS.linux?
