#!/usr/bin/env bash

function getLatestBrew {
	echo "Installing latest homebrew"
	which brew || /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

	brew update
	brew tap 'homebrew/bundle'
}

function brewInstall {
	echo "Installing brews"
	(cd brew && (brew bundle check || brew bundle install))
}

function stowDotfiles {
	echo "Stowing dotfiles"
	ls -d */ | sed 's/\///' | awk {'system("echo " $0); system("stow " $0)'}
}

function mackupRestore {
	echo "Restoring mackup - ensure mackup storage exists"
	MACKUP_DIR=$HOME/Dropbox/Mackup
	if [ ! -d $MACKUP_DIR ]; then
		echo "Mackup storage doesn't exists. exiting." && exit 1	
	fi
	mackup restore
}

function initFish {
        curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish
        source
        fisher
}
function installAsdf {
	git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.6.3
}

function initAsdf {
	echo "Installing asdf plugins"
	(cd asdf && (cat .tool-versions | awk '{system ("asdf plugin-add " $1); system("asdf install " $0)}'))
}

function asdfInstallNode {
	echo "Installing node via asdf"
	brew install coreutils
	brew install gpg
	export GNUPGHOME="${ASDF_DIR:-$HOME/.asdf}/keyrings/nodejs" && mkdir -p "$GNUPGHOME" && chmod 0700 "$GNUPGHOME"
	bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
	(cd asdf && (cat .tool-versions | grep nodejs | xargs asdf install))
}

function makeDirs {
	mkdir -p ~/Dev/src
}

function installTmuxPluginManager {
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
}

function setMacPreferences {
  echo "Setting Mac preferences"

  # Auto hide dock
  defaults write com.apple.dock autohide -bool true
  defaults write com.apple.dock autohide-time-modifier -float 0.5
  defaults write com.apple.dock autohide-delay -float 0

  # Faster key repeat
  defaults write NSGlobalDomain KeyRepeat -int 2
  defaults write NSGlobalDomain InitialKeyRepeat -int 15

  # Trackpad
  defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool false
  defaults write NSGlobalDomain com.apple.swipescrolldirection -bool false
  
  # Mouse
  defaults write -g com.apple.mouse.scaling -float 1.5

  # Use Fn as function keys
  defaults write -g com.apple.keyboard.fnState -bool true

  # Full keyboard access
  defaults write -g AppleKeyboardUIMode -int 2
  
  # Show all extensions
  defaults write NSGlobalDomain AppleShowAllExtensions -bool true
  defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false
  defaults write com.apple.finder FXEnableRemoveFromICloudDriveWarning -bool false

  # Prefer list view in Finder
  defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"
  # Show path bar in Finder
  defaults write com.apple.finder ShowPathbar -bool true

  # Disable dashboard
  defaults write com.apple.dashboard mcx-disabled -bool true

  for app in "Dock" "Finder"; do
    killall "${app}" > /dev/null 2>&1
  done
}


getLatestBrew
brewInstall
stowDotfiles
mackupRestore
initFish
installAsdf
initAsdf
asdfInstallNode
makeDirs
installTmuxPluginManager
setMacPreferences

